# Core layer
FIELD_TEMP = 'temp'
FIELD_FEELS_LIKE = 'feels_like'
FIELD_DEW_POINT = 'dewpoint'
FIELD_HUMIDITY = 'humidity'
FIELD_WIND_SPEED = 'wind_speed'
FIELD_WIND_DIRECTION = 'wind_direction'
FIELD_WIND_GUST = 'wind_gust'
FIELD_BAROMETRIC_PRESSURE = 'baro_pressure'
FIELD_PRECIPITATION = 'precipitation'
FIELD_PRECIPITATION_TYPE = 'precipitation_type'
FIELD_PRECIPITATION_PROBABILITY = 'precipitation_probability'
FIELD_PRECIPITATION_ACCUMULATION = 'precipitation_accumulation'
FIELD_SUNRISE = 'sunrise'
FIELD_SUNSET = 'sunset'
FIELD_VISIBILITY = 'visibility'
FIELD_CLOUD_COVER = 'cloud_cover'
FIELD_CLOUD_BASE = 'cloud_base'
FIELD_CLOUD_CEILING = 'cloud_ceiling'
FIELD_CLOUD_SATELLITE = 'cloud_satellite'
FIELD_SURFACE_SHORTWAVE_RADIATION = 'surface_shortwave_radiation'
FIELD_MOON_PHASE = 'moon_phase'
FIELD_WEATHER_CODE = 'weather_code'
FIELD_WEATHER_GROUPS = 'weather_groups'

# Air quality layer
FIELD_PARTICLE_MATTER25 = 'pm25'
FIELD_PARTICLE_MATTER10 = 'pm10'
FIELD_OZONE = 'o3'
FIELD_NITROGEN_DIOXIDE = 'no2'
FIELD_CARBON_MONOXIDE = 'co'
FIELD_SULFUR_DIOXIDE = 'so2'
FIELD_AIR_QUALITY_INDEX_EPA = 'epa_aqi'
FIELD_PRIMARY_POLLUTANT_EPA = 'epa_primary_pollutant'
FIELD_HEALTH_CONCERN_EPA = 'epa_health_concern'
FIELD_AIR_QUALITY_INDEX_CHINA_MEP = 'china_aqi'
FIELD_PRIMARY_POLLUTANT_CHINA_MEP = 'china_primary_pollutant'
FIELD_HEALTH_CONCERN_CHINA_MEP = 'china_health_concern'

# Pollen layer
FIELD_TREE_POLLEN = 'pollen_tree'
FIELD_WEED_POLLEN = 'pollen_weed'
FIELD_GRASS_POLLEN = 'pollen_grass'

# Road layer
FIELD_ROAD_RISK_SCORE = 'road_risk_score'
FIELD_ROAD_RISK = 'road_risk'
FIELD_ROAD_RISK_CONFIDENCE = 'road_risk_confidence'
FIELD_ROAD_RISK_CONDITIONS = 'road_risk_conditions'

# Fire layer
FIELD_FIRE_INDEX = 'fire_index'

# Insurance layer
FIELD_HAIL_BINARY = 'hail_binary'

CORE_LAYER = [
    FIELD_TEMP,
    FIELD_FEELS_LIKE,
    FIELD_DEW_POINT,
    FIELD_HUMIDITY,
    FIELD_WIND_SPEED,
    FIELD_WIND_DIRECTION,
    FIELD_WIND_GUST,
    FIELD_BAROMETRIC_PRESSURE,
    FIELD_PRECIPITATION,
    FIELD_PRECIPITATION_TYPE,
    FIELD_PRECIPITATION_PROBABILITY,
    FIELD_PRECIPITATION_ACCUMULATION,
    FIELD_SUNRISE,
    FIELD_SUNSET,
    FIELD_VISIBILITY,
    FIELD_CLOUD_COVER,
    FIELD_CLOUD_BASE,
    FIELD_CLOUD_CEILING,
    FIELD_CLOUD_SATELLITE,
    FIELD_SURFACE_SHORTWAVE_RADIATION,
    FIELD_MOON_PHASE,
    FIELD_WEATHER_CODE,
    FIELD_WEATHER_GROUPS,
]

AIR_QUALITY_LAYER = [
    FIELD_PARTICLE_MATTER25,
    FIELD_PARTICLE_MATTER10,
    FIELD_OZONE,
    FIELD_NITROGEN_DIOXIDE,
    FIELD_CARBON_MONOXIDE,
    FIELD_SULFUR_DIOXIDE,
    FIELD_AIR_QUALITY_INDEX_EPA,
    FIELD_PRIMARY_POLLUTANT_EPA,
    FIELD_HEALTH_CONCERN_EPA,
    FIELD_AIR_QUALITY_INDEX_CHINA_MEP,
    FIELD_PRIMARY_POLLUTANT_CHINA_MEP,
    FIELD_HEALTH_CONCERN_CHINA_MEP,
]

POLLEN_LAYER = [
    FIELD_TREE_POLLEN,
    FIELD_WEED_POLLEN,
    FIELD_GRASS_POLLEN,
]

ROAD_LAYER = [
    FIELD_ROAD_RISK_SCORE,
    FIELD_ROAD_RISK,
    FIELD_ROAD_RISK_CONFIDENCE,
    FIELD_ROAD_RISK_CONDITIONS,
]

FIRE_LAYER = [FIELD_FIRE_INDEX]

INSURANCE_LAYER = [FIELD_HAIL_BINARY]
